name: simple_radio
description: A very simple radio app
publish_to: "none"
version: 0.3.1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  http: ^1.2.0
  just_audio: ^0.9.36
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner:
  custom_lint: ^0.5.11
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  total_lints: ^3.2.0

flutter:
  uses-material-design: true
