name: simpleradio
description: A very simple radio app
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_riverpod: ^2.4.9
  http: ^1.1.2
  just_audio: ^0.9.36
  riverpod_annotation: ^2.3.3

dev_dependencies:
  build_runner:
  custom_lint:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  total_lints: ^3.2.0

flutter:
  uses-material-design: true
