name: simple_radio
description: A very simple radio app
publish_to: "none"
version: 0.3.4

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  http: ^1.2.2
  just_audio: ^0.9.40
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.2

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.7
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  total_lints: ^3.4.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/radio_24dp_000000_FILL0_wght400_GRAD0_opsz24.png"
  min_sdk_version: 24
  remove_alpha_ios: true
  web: 
    generate: true
    image_path: "assets/icon/radio_24dp_000000_FILL0_wght400_GRAD0_opsz24.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icon/radio_24dp_000000_FILL0_wght400_GRAD0_opsz24.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/radio_24dp_000000_FILL0_wght400_GRAD0_opsz24.png"